default: &default
  adapter: postgresql
  host: localhost
  username: chris

development:
  <<: *default
  database: flags_server_development

test:
  <<: *default
  database: flags_server_test

production:
  <<: *default
  database: flags_server_production
